# Generated by Django 4.0 on 2022-01-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0007_useravatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='avatar.png', upload_to='avatars'),
        ),
    ]
