# Generated by Django 4.0 on 2022-05-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0016_alter_useravatar_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='/media/avatar.png', upload_to='avatars'),
        ),
    ]
