# Generated by Django 4.0 on 2022-01-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0005_remove_userfollowing_following_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user_id',
            new_name='user',
        ),
    ]
