# Generated by Django 4.0 on 2022-01-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0010_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.CharField(max_length=500),
        ),
    ]
