# Generated by Django 4.0 on 2022-04-21 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0011_alter_comments_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created']},
        ),
    ]
