# Generated by Django 4.0 on 2022-04-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0012_alter_comments_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
