# Generated by Django 4.0 on 2022-05-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0014_alter_userfollowing_following_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravatar',
            name='avatar',
            field=models.ImageField(default='/media/avatar.png', upload_to='avatars'),
        ),
    ]
